server:
  port: 80

#  下边加eureka的配置就是为了能够在eureka注册中心中发现服务提供者
eureka:
  client:
    register-with-eureka: false
    service-url:
#    使用的eureka集群，上一次配置过的
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/